### PR TITLE
Add travis ci

### PR DESCRIPTION
**Pull request by k-okada**
confirmed it passed on https://app.travis-ci.com/github/k-okada/openslam_gmapping/builds/238207518
I also checked on GithubActions, but it is failing for some reason https://github.com/k-okada/openslam_gmapping/actions/runs/1255903406
Once this gets merged, I'll check #37 

cc: @clalancette @seanyen

### CODE REVIEW

**Comment by k-okada** [comment]
build.ros.org fails with network error??
```
17:58:20 Need to get 128 kB/67.6 MB of archives.
17:58:20 After this operation, 275 MB of additional disk space will be used.
17:58:20 Err:1 http://repositories.ros.org/ubuntu/testing bionic/main amd64 ros-melodic-catkin amd64 0.7.29-1bionic.20201014.191449
17:58:20   404  Not Found [IP: 10.0.1.11 80]
17:58:20 E: Failed to fetch http://repositories.ros.org/ubuntu/testing/pool/main/r/ros-melodic-catkin/ros-melodic-catkin_0.7.29-1bionic.20201014.191449_amd64.deb  404  Not Found [IP: 10.0.1.11 80]
17:58:20 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
17:58:20 
17:58:20 Invocation failed due to the following known err
```

**Comment by clalancette** [comment]
> build.ros.org fails with network error??

There was a network problem on the build server, and it failed to upload the packages.  This has all been resolved now, so re-running the PR job (which I'll do next) should work.

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Comment by ahendrix** [comment]
I've approved your request to add Travis-CI integration on this repository; hopefully that helps resolve the Travis-CI issues here.

**Comment by k-okada** [comment]
@ahendrix thank you for your help, but we still need some settings,
Screenshot from 2021-09-28 12-01-12

I think you can find 'Configure' button on the left of "Travis CI" log of this page, and configure it.
Screenshot from 2021-09-28 12-01-19
x

**Comment by ahendrix** [comment]
I spent a while looking into this, and there aren't any settings on the github side which are related to authorization. It appears that Travis-Ci is either installed, or it isn't.

I tried triggering a build manually, on the `melodic-devel` branch, and got an error that the .travis.yml file did not exist.

I was able to trigger a build by closing and reopening this pull request, and I got the same error, "travis ci could not authorize build request for ..."

These are the current github integration settings:

Screen Shot 2021-09-29 at 9 57 22 AM

I did a quick search on the TravisCi error that you're seeing, and this suggests that it's an configuration or plan issue with TravisCi: https://stackoverflow.com/questions/41034694/travis-could-not-authorize-build-request/41078031

**Comment by k-okada** [comment]
@ahendrix Thank for taking time, Yes you're right , setting free plan make start tarvic-ci. Great!
Screenshot from 2021-09-30 10-25-57
t

**Pull request merged**
