### PR TITLE
Add RoboStack CI

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
As discussed in https://github.com/ros-perception/openslam_gmapping/pull/34 this aims to provide cross-platform (Win, MacOS and Linux) integration.

@wolfv @traversaro - do you have any idea why the builds are not being triggered? Are there some changes needed to enable GitHub actions in the repo first?

**Comment by Tobias-Fischer** [comment]
Okay, all fixed now.

@k-okada this is ready for review. You can see an an example run [here](https://github.com/Tobias-Fischer/openslam_gmapping/actions/runs/1301800621). Once merged in, this will run in the melodic-devel branch as well as on pull requests.

**Comment by k-okada** [comment]
@Tobias-Fischer great!. It worked as expected, https://github.com/k-okada/openslam_gmapping/actions/runs/1306534586. 

```
  push:
    branches:
      - master
      - "[kmn]*-devel"
      - patch-2 <<<<<<<<<<<<<< should we remove this?
```

**Comment by Tobias-Fischer** [comment]
Done.

**Comment by k-okada** [comment]
@Tobias-Fischer thank you!

**Comment by wolfv** [comment]
Awesome!

**Pull request merged**
