### PR TITLE
[melodic-devel] Windows bringup

### PR DESCRIPTION
**Pull request by seanyen**
* Follow catkin guide to install libraries and executables to portable locations.
  https://docs.ros.org/api/catkin/html/howto/format1/building_libraries.html#installing
  https://docs.ros.org/api/catkin/html/howto/format1/building_executables.html#installing
* Replace GCC-specific `__PRETTY_FUNCTION__` with C++11 standard `__func__`.
* Adding [visibility control](https://gcc.gnu.org/wiki/Visibility), which is required to create shared libraries on Windows, by using CMake `GenerateExportHeader` convention.
* Conditionally guard many Linux\POSIX-only header inclusion with `#ifndef _WIN32`.

This change is verified to build with http://wiki.ros.org/Installation/Windows.

### CODE REVIEW

**Comment by seanyen** [comment]
@k-okada This is ready for review. Let me know any feedback. Thanks!

**Comment by seanyen** [comment]
@k-okada Friendly ping.

**Comment by Tobias-Fischer** [comment]
Friendly ping @k-okada - it would be great to see this merged!

**Review by k-okada — APPROVED** [review]
thank  you, I also checked this PR passed test codes in https://github.com/ros-perception/slam_gmapping

**Comment by k-okada** [comment]
@seanyen @Tobias-Fischer BTW, if you know how to configure CI for Windows, please let me know. I am pretty sure that someone will brake the Windows build in future, because most of people only compile on their Ubuntu machine.

**Comment by Tobias-Fischer** [comment]
Hi, in moveit we setup a cross-platform CI (Linux+OSX+Win) using the Robostack project. It's just around adding to simple files that run a GitHub action: https://github.com/ros-planning/moveit/blob/master/.github/workflows/cross_platform_ci.yml and https://github.com/ros-planning/moveit/blob/master/.github/ci_cross_platform_env.yml

/cc @wolfv @traversaro

**Comment by k-okada** [comment]
@Tobias-Fischer great, @seanyen could you create windows script to compile openslam_gmapping ?

**Pull request merged**
